# Generated by Django 6.0.8 on 2026-09-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('minimum_instructors', models.PositiveSmallIntegerField(default=1)),
                ('recommended_instructors', models.PositiveSmallIntegerField(default=1)),
                ('instructor_intensive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('county', 'County'), ('academy', 'State academy')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('travel_preference', models.CharField(choices=[('contact', 'Contact me as needed'), ('local', 'Home organization only'), ('limited', 'Limited travel')], default='contact', max_length=16)),
                ('travel_notes', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('home_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='scheduling.organization')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('unavailable', 'Unavailable'), ('tentative', 'Tentatively available')], max_length=16)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='scheduling.instructor')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='scheduling.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='proposed', max_length=16)),
                ('location_name', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('contact_name', models.CharField(blank=True, max_length=140)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('acadis_registration_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='scheduling.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_events', to=settings.AUTH_USER_MODEL)),
                ('host_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_events', to='scheduling.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead instructor'), ('assistant', 'Assistant instructor')], max_length=16)),
                ('instructors_needed', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assistance_requests', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='scheduling.trainingevent')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location_override', models.CharField(blank=True, max_length=180)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.trainingevent')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_lead', models.BooleanField(default=True)),
                ('can_assist', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending verification'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_authorizations', to='scheduling.course')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_course_authorizations', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_authorizations', to='scheduling.instructor')),
            ],
            options={
                'ordering': ('course__name', 'instructor__last_name'),
                'constraints': [models.UniqueConstraint(fields=('instructor', 'course'), name='unique_instructor_course_authorization')],
            },
        ),
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead instructor'), ('assistant', 'Assistant instructor')], max_length=16)),
                ('confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.instructor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='scheduling.trainingsession')),
            ],
            options={
                'ordering': ('session__starts_at', 'role', 'instructor__last_name'),
                'constraints': [models.UniqueConstraint(fields=('session', 'instructor'), name='unique_session_instructor_assignment')],
            },
        ),
    ]
