# Generated by Django 6.0.8 on 2026-09-01 18:37

import django.db.models.deletion
from django.db import migrations, models
import re


ORDINAL_VALUES = {"1st": 1, "2nd": 2, "3rd": 3, "4th": 4, "5th": 5, "6th": 6}


def unit_count(value):
    normalized = (value or "").strip().rstrip("`")
    if not re.fullmatch(r"\d+(?:\.0+)?", normalized):
        return None
    count = int(float(normalized))
    return count if count > 0 else None


def expand_numbers(text, count):
    normalized = re.sub(r"\s+", " ", text.replace("–", "-").replace("—", "-"))
    numbers = set()
    ranges = re.compile(r"(?<!\d)(\d+)\s*(?:-|thru|through|to)\s*(\d+)(?!\d)", re.I)
    for match in ranges.finditer(normalized):
        start, end = int(match.group(1)), int(match.group(2))
        if start > end:
            start, end = end, start
        numbers.update(range(start, end + 1))
    normalized = ranges.sub(" ", normalized)
    numbers.update(int(value) for value in re.findall(r"\d+", normalized))
    return {number for number in numbers if 1 <= number <= count}


def staffing_by_unit(count, instructor_text, safety_text):
    staffing = {number: [1, False] for number in range(1, count + 1)}
    requirements = re.sub(r"\s+", " ", instructor_text or "").strip()
    ordinal = r"(?:SFI\s*)?(?:1st|2nd|3rd|4th|5th|6th)"
    rank_group = rf"{ordinal}(?:\s*(?:&|,|and)\s*{ordinal})*"
    clauses = list(re.finditer(
        rf"(?P<ranks>{rank_group})\s*-\s*Units?\s*(?P<units>.*?)(?={rank_group}\s*-\s*Units?|$)",
        requirements,
        re.I,
    ))
    for clause in clauses:
        ranks = [ORDINAL_VALUES[value.lower()] for value in re.findall(r"1st|2nd|3rd|4th|5th|6th", clause.group("ranks"), re.I)]
        required = max(ranks) if ranks else 1
        for number in expand_numbers(clause.group("units"), count):
            staffing[number][0] = max(staffing[number][0], required)
    if not clauses:
        ranks = [ORDINAL_VALUES[value.lower()] for value in re.findall(r"1st|2nd|3rd|4th|5th|6th", requirements, re.I)]
        if ranks:
            for values in staffing.values():
                values[0] = max(ranks)
    safety = re.sub(r"\s+", " ", safety_text or "").strip()
    if safety and safety.upper() not in {"N/A", "NA", "NONE"}:
        if re.search(r"all\s+units", safety, re.I):
            safety_units = set(staffing)
        elif re.search(r"units?", safety, re.I):
            safety_units = expand_numbers(re.split(r"units?", safety, maxsplit=1, flags=re.I)[-1], count)
        else:
            safety_units = set()
        for number in safety_units:
            staffing[number][1] = True
    return staffing


def seed_course_units(apps, schema_editor):
    Course = apps.get_model("scheduling", "Course")
    CourseUnit = apps.get_model("scheduling", "CourseUnit")
    TrainingEvent = apps.get_model("scheduling", "TrainingEvent")
    TrainingSession = apps.get_model("scheduling", "TrainingSession")
    for course in Course.objects.all():
        count = unit_count(course.number_of_units)
        if not count:
            continue
        staffing = staffing_by_unit(count, course.instructor_requirements, course.safety_officer_requirements)
        for number, values in staffing.items():
            CourseUnit.objects.get_or_create(
                course=course,
                unit_number=number,
                defaults={
                    "required_instructors": values[0],
                    "requires_safety_officer": values[1],
                },
            )
        units = list(CourseUnit.objects.filter(course=course).order_by("unit_number"))
        for event in TrainingEvent.objects.filter(course=course):
            sessions = list(TrainingSession.objects.filter(event=event).order_by("starts_at", "pk"))
            for session, unit in zip(sessions, units):
                session.course_unit = unit
                session.save(update_fields=("course_unit",))
            TrainingSession.objects.bulk_create([
                TrainingSession(event=event, course_unit=unit)
                for unit in units[len(sessions):]
            ])


def unseed_course_units(apps, schema_editor):
    TrainingSession = apps.get_model("scheduling", "TrainingSession")
    CourseUnit = apps.get_model("scheduling", "CourseUnit")
    TrainingSession.objects.update(course_unit=None)
    CourseUnit.objects.all().delete()


class Migration(migrations.Migration):

    # PostgreSQL cannot create the later partial index in the same transaction
    # after the data migration updates TrainingSession foreign keys.
    atomic = False

    dependencies = [
        ('scheduling', '0009_recurring_availability_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ('course_unit__unit_number', 'starts_at')},
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead instructor'), ('assistant', 'Assistant instructor'), ('safety', 'Safety officer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='instructorassignment',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead instructor'), ('assistant', 'Assistant instructor'), ('safety', 'Safety officer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=180)),
                ('required_instructors', models.PositiveSmallIntegerField(default=1)),
                ('requires_safety_officer', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='scheduling.course')),
            ],
            options={
                'ordering': ('unit_number',),
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='course_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='scheduling.courseunit'),
        ),
        migrations.RunPython(seed_course_units, unseed_course_units),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('course_unit__isnull', False)), fields=('event', 'course_unit'), name='unique_event_course_unit_session'),
        ),
        migrations.AddConstraint(
            model_name='courseunit',
            constraint=models.UniqueConstraint(fields=('course', 'unit_number'), name='unique_course_unit_number'),
        ),
        migrations.AddConstraint(
            model_name='courseunit',
            constraint=models.CheckConstraint(condition=models.Q(('required_instructors__gte', 1)), name='course_unit_requires_instructor'),
        ),
    ]
