# Generated by Django 6.0.8 on 2026-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_course_units_and_staffing'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='sfi_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='SFI number'),
        ),
    ]
