# Generated by Django 6.0.8 on 2026-09-04 13:28

import django.db.models.deletion
from django.db import migrations, models


def normalize_name(value):
    return "".join(character for character in (value or "").casefold() if character.isalnum())


def backfill_organization_scope(apps, schema_editor):
    Organization = apps.get_model("scheduling", "Organization")
    for organization in Organization.objects.all():
        organization.normalized_name = normalize_name(organization.name)
        if organization.kind == "county":
            organization.county_name = organization.name.removesuffix(" County").strip()
        organization.save(update_fields=("normalized_name", "county_name"))


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_alter_instructor_sfi_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('normalized_name', models.CharField(db_index=True, max_length=180)),
                ('county_name', models.CharField(blank=True, db_index=True, max_length=60)),
                ('source_fdid_code', models.CharField(blank=True, max_length=12, verbose_name='Former FDID code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('county_name', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('display_order', 'kind', 'county_name', 'name')},
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='county_name',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='organization',
            name='directory_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='fdid_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, verbose_name='FDID code'),
        ),
        migrations.AddField(
            model_name='organization',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('merged', 'Merged into another agency'), ('retired', 'Retired')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='County or statewide authority responsible for this organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='scheduling.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='The active organization that succeeded this merged or retired entry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predecessors', to='scheduling.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('state', 'Statewide authority'), ('county', 'County'), ('academy', 'State academy'), ('agency', 'Fire department / agency')], max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.RunPython(backfill_organization_scope, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('kind', 'county_name', 'normalized_name'), name='unique_organization_name_in_scope'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('fdid_code', ''), _negated=True), fields=('county_name', 'fdid_code'), name='unique_organization_fdid_in_county'),
        ),
        migrations.AddField(
            model_name='organizationalias',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='scheduling.organization'),
        ),
        migrations.AddConstraint(
            model_name='organizationalias',
            constraint=models.UniqueConstraint(fields=('county_name', 'normalized_name'), name='unique_organization_alias_in_county'),
        ),
    ]
