# Generated by Django 6.0.8 on 2026-09-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Organization administrator'), ('viewer', 'Read-only viewer')], max_length=24)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='scheduling.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('organization__name', 'user__last_name', 'user__first_name'),
                'constraints': [models.UniqueConstraint(fields=('user', 'organization', 'role'), name='unique_user_organization_role')],
            },
        ),
    ]
