# Generated by Django 6.0.8 on 2026-09-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_duplicate_emails_and_enforce_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='sfi_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='SFI number'),
        ),
    ]
