# Generated by Django 6.0.8 on 2026-09-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_instructorapplication_sfi_number'),
        ('scheduling', '0015_organizationalias_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Not approved'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16)),
                ('signup_source', models.CharField(choices=[('general', 'NYSFIRETOOLS protected tools'), ('scheduler', 'Fire Training Scheduler'), ('admin', 'Administrator-created'), ('legacy', 'Existing account')], default='general', max_length=16)),
                ('scheduler_status', models.CharField(choices=[('not_enrolled', 'Not enrolled'), ('pending', 'Enrollment pending'), ('active', 'Enrolled'), ('rejected', 'Enrollment not approved')], db_index=True, default='not_enrolled', max_length=16)),
                ('requested_organization_name', models.CharField(blank=True, max_length=180)),
                ('access_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_profiles', to='scheduling.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nysfiretools_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
